<html>

<h1>La migración del triángulo norte centroamerico en los últimos años</h1>
<h4>El siguiente texto es cortesía de la coordinación de Historia de la Universidad Iberoamericana</h4>
<p>La migración en Centroamérica ha sido una constante, no únicamente por la confluencia con México, sino también por las condiciones socioeconómicas –y en momentos políticas- de la región que ven en Estados Unidos una oportunidad. El llamado triángulo norte centroamericano –Guatemala, El Salvador, Honduras-, ha sobrevivido a episodios de violencia social y racial extrema, que ha obligado a salir a su población. Entre la década de los setenta y ochenta se vieron obligados a huir por las guerras civiles que sufrían.</p>
<p>México fue uno de los países que les otorgaron refugio y la posibilidad de establecerse de manera regular en su territorio. Sin embargo, migraciones pasadas dejaron redes sólidas que facilitaban la movilización hacia Estados Unidos, sumado a que las condiciones económicas eran más favorables en aquel país. De ahí que el tránsito de salvadoreños, guatemaltecos y hondureños –en ese orden- por México no sea extraño[1]. </p>
<p>Es de destacar que, al compartir frontera con México, la tradición de tránsito de guatemaltecos se remonta al inicio del siglo XX. Las poblaciones limítrofes con la frontera sur mexicana, tienen la autorización de entrar y salir de aquel país con fines laborales y tradicionalmente los ingresaban a la zona de Soconusco en Chiapas para trabajar en la cosecha del café. </p>
<p>Estas movilizaciones fueron tema de conversación regional hasta finales de los noventa, en los que hubo la sensación del aumento de los flujos. Esto quizá porque se esperaba que después de la firma de los acuerdos de paz en El Salvador (1992) y Guatemala (1996) la población que huyó regresaría a su zona de origen, pero no fue así. La firma de los acuerdos de paz fue un proceso puramente formal, que no fue acompañado de procesos de reconciliación ni reparación a las víctimas. Además la población más joven se quedó atrapada dentro de formaciones militares sin orden, pero armados, y con muy pocas expectativas laborales o de educación.</p>
<p>En países como Guatemala, Honduras y El Salvador la tasa de asesinatos por día asciende a 40, tres veces el promedio mundial. Circula un aproximado de 4.5 millones de armas de fuego no registradas o ilegales, provenientes en su mayoría de Norteamérica. La falta de proyectos socioeconómicos en la región, potenció la salida de la población hacia Estados Unidos, en busca de “una mejor vida”. </p>
<p>Se pueden distinguir dos momentos claros en las oleadas de migrantes hacia Estados Unidos desde estos países en las últimas décadas: la migración en tiempos de conflictos armados, para escapar del clima de violencia y de persecución política; y la etapa posterior a la cese de los conflictos armados, y firmas de los acuerdos de paz, cuando pasada la ilusión de la paz, las redes que se consolidaron en el pasado aunado a factores asociados a las precariedades del mercado de trabajo, la desigualdad social, las nuevas confrontaciones políticas, la desaceleración de la economía, los desastres naturales y, más recientemente, la violencia social, han sido los detonantes del éxodo hacia los países del norte en búsqueda de mejoras en la calidad de vida de ellos y sus familias.  </p>
<p>A inicios del presente siglo, los ataques terroristas en Estados Unidos agudizaron los controles y obstáculos para la migración –regular, irregular y tránsito- en la región. Entonces los ojos estaban puestos en estos flujos, y se empezaron a convertir en un problema. En este contexto, México se vería obligado a endurecer sus controles y evitar que entre los migrantes atravesaran posible terroristas con intenciones de atentar contra la seguridad estadounidense. A partir de entonces y hasta ahora, el panorama cambió en detrimento de los migrantes –sobre todo centroamericanos-. </p>

<h1>La política de los países de los vecinos del Norte.</h1>
<p>Como se ha repetido en varios informes y en testimonios de los propios migrantes  en México son cometidos una gran cantidad de abusos en contra de los centroamericanos [http://200.33.14.34:1033/archivos/pdfs/Var_22.pdf] [http://www.cndh.org.mx/sites/all/doc/Informes/Especiales/2011_secmigrantes.pdf] [http://www.acnur.org/fileadmin/Documentos/Publicaciones/2014/9484.pdf?view=1] [https://ia800300.us.archive.org/27/items/Libro-NuestrasVocesEnElCamino-Imumi/NuestrasVocesEnElCamino-Imumi.pdf] [http://www.sjmmexico.org.mx/presentacion-del-informe-redodem-el-estado-indolente/] [https://vimeo.com/search?q=mujeres+transmigrantes] . En general, están vinculados con el crimen organizado, relacionado con el contrabando, trata de personas o tráfico de drogas, en contubernio o bajo la indiferencia de las autoridades municipales, estatales y federales. Este tipo de situaciones, junto con aseguramientos de dudosa legitimidad, se repite a lo largo de la frontera de México. La detención se ha convertido en el instrumento de la política migratoria mexicana y por tanto se le está dando un enfoque de control y represión. </p>
<p class="quote">El reciente endurecimiento de las Normas para el Funcionamiento de las Estaciones Migratorias (2009) es un claro ejemplo de los efectos del enfoque de seguridad nacional que afecta directamente las vidas de las personas detenidas en las estaciones migratorias. A raíz de la aplicación de éstas, los procesos y las consecuencias de la detención administrativa se han vuelto aún menos transparente debido a la ausencia de monitoreo civil de la situación en las estaciones migratorias y por las restricciones para el acceso de los representantes legales (Bonnici, 2011: 388)</p>
<p>Dicha cuestión ha sido confirmada en entrevista con personal de Sin Fronteras. El único cambio registrado sería que, a partir de 2009, la migración irregular en tránsito ya no está tipificada como delito, sino como falta administrativa que conlleva a una multa y la detención inmediata, pero en la práctica se continúa criminalizando al migrante, quien por su situación de vulnerabilidad no se atreve a denunciar. </p>
<p>Además, la política mexicana de seguridad fronteriza viene dictada desde Estados Unidos, que a partir de 2001 ha incrementado controles y represión fronteriza, y ha exigido lo mismo a México en su frontera sur. Y desde 2001, con el inicio de una nueva etapa represiva desde Washington, aumentó la vigilancia, deportaciones, persecución y estigmatización de los migrantes –mexicanos y centroamericanos- tanto residentes o de reciente llegada a Estados Unidos.</p>
<p>Creció el presupuesto de la Patrulla Fronteriza y del Servicio de Inmigración y Naturalización (INS, por sus siglas en inglés) y se lanzaron varias operaciones que reforzaban la seguridad fronteriza –Bloqueo, El Paso, Guardián San Diego. Para la primera década de este siglo las horas de vigilancia aumentaron en un 74%, el presupuesto en 52% y las deportaciones en 32% (Massey et al., 2009; Massey et al., 2002; Chávez, 2001; Dobbs, 2006). El aumento de las deportaciones superó los peores años antiinmigrantes -en 1930 se contabilizaron 139 mil deportaciones, frente a las 500 mil por año de la era Obama. La política política de inmigración pasaría del control migratorio al tema de la defensa de la seguridad nacional, lo que ha traído múltiples efecto, entre ellos la creciente oleada de deportaciones:  </p>
<p class="quote">Recordemos que una de las justificaciones ideológicas más notorias de las medidas restrictivas que multiplican las de­portaciones es la guerra contra el terrorismo, que condujo, tras el fatídico 9/11, a la fusión del servicio de inmigración, la guardia costera y la patrulla fronteriza en una sola enti­dad: el Department of Homeland Security. (Rocha, 2012:6)</p>
<p>Y entre los latinoamericanos, los centroamericanos han sido especial objeto de deportaciones o repatriaciones forzadas en las últimas décadas.</p>
<p class="quote">Los centroamericanos que quieren vivir el sueño americano son abruptamente despertados a una pesadilla de redadas, prisiones y deportaciones. Y así, en un mundo donde se habla de mercados laborales globalizados, después de ser mano de obra excedente en su países de origen –no los “absorbe” la inversión externa y los tentáculos de las transnacionales–, tampoco consiguen ser reciclados en los países de destino, que los expulsan.  (Rocha, 2012: 6)</p>
<p>La idea de que la migración irregular era un peligro para la seguridad de Estados Unidos se reforzó gracias a los medios de comunicación que abordaban el tema desde una retórica alarmista: inundación, oleada, invasión. Por lo tanto, la frontera se convirtió en un campo de batalla, en el que Estados Unidos ejercía su poder castrense para cuidar la seguridad interna. Así se dio un cambio en las rutas de paso y el incremento de los costos y riesgos del cruce.</p>
<p>Los migrantes son víctimas de secuestros, violaciones sexuales, golpizas y extorsión, perpetrados en contubernio o con la aprobación de la autoridad. Los narcotraficantes se han sumado a la ruta[2]quizá porque algunos migrantes empezaron a utilizar rutas tradicionales de contrabando de mercancías y drogas, intentando cambiar el recorrido por la alta seguridad fronteriza. Debido a la clandestinidad de los delitos y la falta de denuncia, no existen registros de estas prácticas, solamente testimonios recabados por la Comisión Nacional de Derechos Humanos (CNDH) o Amnistía Internacional (AI) en los albergues a lo largo del camino. Según datos de la CNDH los secuestros suceden sobre todo en la zona sur del país, en Veracruz y Tabasco principalmente, pero también en Oaxaca y Chiapas; luego le sigue el norte –Tamaulipas, Coahuila, Chihuahua, Sonora, Nuevo León y San Luis Potosí-, el centro –Puebla, Estado de México, Guanajuato, Tlaxcala y la Ciudad de México- y hay un porcentaje sobrante que no se ha identificado. La mayor parte de los testimonios identifican a los Zetas como los perpetradores de los secuestros desde Veracruz hasta la frontera norte.</p>

<h1>En el origen: la ineptitud de los países de la región.</h1>
<p>En el caso de El Salvador, la envergadura del retorno ha sido tal que el estado salvadoreño ha tenido que responder con políticas públicas e institucionales para atender este fenómeno, como parte de estos esfuerzos surge el programa Bienvenido a Casa que recibe a cientos de salvadoreños casi a diario y les presta una serie de servicios tendientes a favorecer el proceso de reintegración.</p>
<p>En los últimos años el ritmo de las deportaciones ha sido constante. Conforme a las cifras oficiales en el sitio de la Dirección General de Migración y Extranjería de El Salvador, el número de repatriados totales en el año 2013 fue de 36,056 personas -20,111 eventos vía terrestre y 15,690 eventos por tierra-, cifra aumentada en 4,245 eventos conforme las cifras para el año 2012, a su vez aumentada en 6,108 eventos respecto al año 2011. En El Salvador, han representado más de 93 mil personas devueltas al país de manera involuntaria, más de 93 mil proyectos migratorios truncados, que traen consigo el drama de la reinserción a un entorno que, en muchas ocasiones, es aún más agreste que el que les hizo tomar la decisión de partir.</p>
<p>El gobierno hondureño, que tomó posesión hace escasamente un año, ha planteado acciones paliativas ante el número de deportados que está recibiendo–más de 80 mil al año-, desde Estados Unidos y México. Entre ellas se destacan el Plan Alianza para la prosperidad, firmado en noviembre de 2014 con los presidentes Otto Pérez Molina (Guatemala), Salvador Sánchez Cerén (El Salvador) y el presidente hondureño, Juan Orlando Hernández. Además emprendió Fuerza de Tarea del Niño Migrante, para la atención de menores.</p>
<p>Asimismo, en julio de 2014 lanzó una declaratoria de emergencia humanitaria por decreto que facilitó la atención de población deportada. A través del Comisionado Permanente de Contingencias (COPECO), con apoyo de UNICEF y las municipalidades de San Pedro Sula, se plantearon acciones de emergencia humanitaria ante el número de deportados. En julio de 2014 ubicaron carpas especiales para asistencia humanitaria que contaban con condiciones de infraestructura de alta calidad, para recibir a las familias e infantes en el aeropuerto Ramón Villeda Morales. El albergue principal se instaló en San Pedro Sula.</p>
<p>Paralelamente, lanzó programas de inserción laboral –Con chamba vivís mejor-, apoyos económicos a familias de bajos recursos –Bono Diez Mil- y la garantía de reincorporación a la escuela de los niños deportados. Sin embargo, si los índices de violencia, precariedad laboral y social no disminuyen, el éxito de estas iniciativas está en duda. </p>
<p>En Guatemala la OIM hasta 2013 se encargó de la recepción de los deportados, otorgándoles un teléfono para llamar a su familia, e  información general de transporte a comunidades fuera de la capital. Cuando la OIM retiró su apoyo a esta iniciativa, cinco profesionales de dicha organización formaron la Asociación de Apoyo Integral al Migrante (AIM) para continuar con la labor iniciada. Pero, ante el incremento de las deportaciones, el gobierno se unió con otras organizaciones -Consejo Nacional de Atención al Migrante de Guatemala (CONAMIGUA), Banco de Desarrollo Rural (Banrural), Centro para la Acción de la Responsabilidad Social Empresarial (CentrRSE), Comisión del Migrante del Congreso de la República de Guatemala, la emprea Transactel y el Instituto Técnico de Capacitación y Productividad (INTECAP), para implementar en noviembre 2013 el programa Bienvenido a Casa, con una duración de dos años. </p>
<p>La primera asistencia del programa es poner a disposición de los retornados dos teléfonos para hacer llamadas locales y a Estados Unidos –donadas por FLACSO- y orientar a quienes no saben qué hacer. Además, establece la importancia de generar oportunidades en el país, para facilitar la incorporación laboral y social de los migrantes y sus familias. Unas 150 empresas se han sumado a esta iniciativa con el objetivo de generar empleos, generalmente en servicios de centros de llamadas –por sus habilidades en inglés-, construcción, soldadura, plomería y cocina.</p>
<p>Las cifras de deportaciones superan los 80 mil por año, las dinámicas son distintas, mientras que en México las detenciones se realizan a migrantes en tránsito, en Estados Unidos se realizan contra migrantes establecidos de manera irregular. La misma situación se repite en el caso de los menores, aunque existe un subregistro entre aquellos que son deportados como adultos –situación que se repite en el caso hondureño y salvadoreño-.</p>
<p>La magnitud del fenómeno y su complejidad han hecho que las respuestas institucionales no den abasto, y hacen necesario generar nuevas respuestas más integrales ante una realidad creciente que, al menos en el mediano plazo, no parece dar muestras de disminuir. Este es el punto de partida de la presente investigación, que propone un estudio de la situación actual de este fenómeno y de las historias después del retorno de jóvenes y niños, describiendo las rutas migratorias e historias de centroamericanos que han visto truncado su proyecto de emigrar, y se enfrentar al escenario no elegido del retorno a su país.</p>

</html>


